version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - br0
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@test.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "3005:80"
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:your_password_here@db:5432/your_database_name_here

volumes:
  postgres-data:
networks:
  br0:
    driver: bridge